name: Build and Deploy BlazorTry1814 to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Publish app
      run: dotnet publish -c Release './BlazorTry1814/BlazorTry1814.csproj'

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ./BlazorTry1814/bin/Release/net5.0/publish/wwwroot/index.html
        base_href: /ASP.NET-Core-5-for-Beginners/

    - name: Save artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: myWASM
        path: './BlazorTry1814/bin/Release/net5.0/publish/wwwroot'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create pages branch
        continue-on-error: true
        run: |
          git config --global user.name "KhorAMus"
          git config --global user.email "khoramus@yandex.ru"
          git checkout -B pages
      - name: Clear pages branch
        continue-on-error: true
        run: |
          git rm -rf .
          git commit --allow-empty -m "root commit"
          git push -f origin pages
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: myWASM
      - name: Commit changes
        run: |
          git add .
          git commit -m "publishing WASM"
          git push --set-upstream origin pages